// Writes src/data_photos.js from tools/images.json + tools/sources.json (credit, license, illustration flag).
import fs from "fs";
const meta = JSON.parse(fs.readFileSync("tools/images.json", "utf8"));
const src = JSON.parse(fs.readFileSync("tools/sources.json", "utf8"));
const out = {};
for (const [k, m] of Object.entries(meta)) {
  if (!fs.existsSync(`img/${k}.jpg`)) continue;
  out[k] = { by: m.author, lic: m.license, page: m.page, ...(src[k] && src[k].ill ? { ill: 1 } : {}), ...(src[k] && src[k].pos ? { pos: src[k].pos } : {}) };
}
fs.writeFileSync("src/data_photos.js", "/* generated by tools/gen-photos.mjs: photo credits (Wikimedia Commons) */\nDATA.photos = " + JSON.stringify(out, null, 0).replace(/},"/g, '},\n  "') + ";\n");
console.log(Object.keys(out).length, "photos");
