DATA.phrases = [
  { ja: "英語のメニューはありますか？", ro: "Eigo no menyū wa arimasu ka?", he: "יש תפריט באנגלית?" },
  { ja: "おすすめは何ですか？", ro: "Osusume wa nan desu ka?", he: "מה אתם ממליצים?" },
  { ja: "これをください。", ro: "Kore o kudasai.", he: "את זה, בבקשה (ומצביעים)" },
  { ja: "お水をください。", ro: "Omizu o kudasai.", he: "מים, בבקשה" },
  { ja: "カードで払えますか？", ro: "Kādo de haraemasu ka?", he: "אפשר לשלם בכרטיס אשראי?" },
  { ja: "お会計をお願いします。", ro: "Okaikei o onegai shimasu.", he: "את החשבון, בבקשה" },
  { ja: "ごちそうさまでした。", ro: "Gochisōsama deshita.", he: "תודה על הארוחה (אומרים ביציאה)" },
];
DATA.dishes = [
  { h: "מה לטעום בכל מקום", items: [
    "טוקיו: סופלה פנקייק, סושי מסוע, ראמן",
    "קיוטו: ממתקי מאצ'ה, טמאגויאקי ב-Nishiki, יודופו בארשיאמה",
    "קנזאווה: גלידה בעלה זהב, קנזאווה אודן, <span lang=ja>kaisendon</span> ב-Omicho",
    "טקאיאמה: Hida beef, וסושי Hida beef על קרקר אורז",
    "Okuhida: ארוחת קאיסקי בריוקאן",
    "מצומוטו: שינשו סובה"] },
  { h: "נימוסים קטנים", items: [
    "לא משאירים טיפ. זה נחשב מוזר",
    "משלמים בקופה, לא לשולחן. בהרבה מקומות מניחים את הכסף במגש הקטן",
    "במסעדות ראמן רבות מזמינים מראש במכונה בכניסה",
    "לא הולכים ואוכלים ברחוב. אוכלים ליד הדוכן",
    "מקומות קטנים ודוכנים בשווקים עובדים לפעמים רק במזומן"] },
];
/* food:<region> lists. src: "sheet" = from the sheet, "sug" = suggestion */
[
  ["tokyo", "שיבויה", "Hoshino Coffee", "בית קפה", "sheet", "ליד פסל Hachiko. לטעום את הסופלה פנקייק המפורסם.", "Hoshino Coffee Shibuya"],
  ["tokyo", "שיבויה", "The SG Club", "בר", "sheet", "תשע דקות מהמלון. אדום בגיליון.", "The SG Club, Shibuya", { red: 1 }],
  ["tokyo", "שיבויה", "The Bellwood", "בר", "sheet", "בר מאוד שווה, מקום 48 בעולם. אדום בגיליון.", "The Bellwood, Shibuya", { red: 1 }],
  ["tokyo", "הארג'וקו ואומוטסנדו", "Kaiten Sushi Ginza", "סושי מסוע", "sheet", "סושי מסוע עם כוכב מישלן.", "Ginza Onodera Kaiten Sushi, Omotesando"],
  ["tokyo", "הארג'וקו ואומוטסנדו", "Menchirashi", "אודון", "sheet", "אודון קרבונרה.", "Menchirashi, Harajuku"],
  ["tokyo", "הארג'וקו ואומוטסנדו", "Luke's Lobster", "כריכי לובסטר", "sheet", "", "Luke's Lobster Omotesando"],
  ["tokyo", "הארג'וקו ואומוטסנדו", "רחוב Takeshita", "אוכל רחוב", "sheet", "רחוב אוכל צבעוני, טוסט קשת בענן.", "Takeshita Street"],
  ["tokyo", "שינג'וקו", "Isetan Shinjuku", "כלבו אוכל", "sheet", "כלבו אוכל ענק, עם חנות השוקולד <b>Jean-Paul Hévin</b>.", "Isetan Shinjuku"],
  ["tokyo", "שינג'וקו", "Bam Bi Coffee", "בית קפה", "sheet", "קפה ופנקייק יפני אוורירי.", "bam bi coffee, Shinjuku"],
  ["tokyo", "שינג'וקו", "odeo shinjukuminami guchiten", "סושי מסוע", "sheet", "אופציה לצהריים.", ""],
  ["tokyo", "שינג'וקו", "Omoide Yokocho", "ברים", "sheet", "רחוב הברים, לערב.", "Omoide Yokocho"],
  ["tokyo", "גינזה וצוקיג'י", "Ginza Hachigou", "ראמן", "sheet", "אופציה לצהריים ב-3.11.", "Ginza Hachigou"],
  ["tokyo", "גינזה וצוקיג'י", "Tsukiji Outer Market", "שוק", "sheet", "בוקר של 4.11. להגיע לפני 9:00, רוב הדוכנים נסגרים עד 14:00.", "Tsukiji Outer Market"],
  ["tokyo", "גינזה וצוקיג'י", "קומת האוכל ב-Mitsukoshi", "כלבו אוכל", "sheet", "קומה תת-קרקעית של אוכל ומתוקים.", "Ginza Mitsukoshi"],
  ["tokyo", "גינזה וצוקיג'י", "ארוחה שווה בגינזה", "ערב חגיגי", "sheet", "4.11 בערב. עוד לא נבחר מקום, ברשימת ההזמנות.", "", { red: 1, bookAhead: 1, book: "tb-ginza-dinner" }],
  ["kyoto", "מרכז העיר", "Nishiki Market", "שוק", "sug", "טמאגויאקי, תמנון קטן על שיפוד עם ביצה בפנים, וממתקי מאצ'ה. נסגר בסביבות 17:00-18:00.", "Nishiki Market, Kyoto"],
  ["kyoto", "מרכז העיר", "סמטת Pontocho", "ארוחת ערב", "sug", "מסעדות לאורך הנהר.", "Pontocho Alley"],
  ["kyoto", "מרכז העיר", "Kawaramachi ו-Kiyamachi", "ארוחת ערב", "sug", "אזור עם הרבה מסעדות, קרוב לרוב המלונות.", "Kiyamachi Street, Kyoto"],
  ["kyoto", "היגשיאמה", "סטארבקס בבית עץ", "בית קפה", "sug", "ב-Ninenzaka, עם חדרי טטאמי.", "Starbucks Kyoto Ninenzaka Yasaka Chaya"],
  ["kyoto", "ארשיאמה", "יודופו או סובה", "צהריים", "sug", "יודופו (טופו חם) הוא מאכל מקומי של ארשיאמה.", ""],
  ["alps", "קנזאווה", "גלידה בעלה זהב", "מתוק", "sug", "ב-Higashi Chaya.", "Higashi Chaya District"],
  ["alps", "קנזאווה", "בית התה Shima", "בית תה", "sug", "בית תה היסטורי ב-Higashi Chaya.", "Shima Teahouse, Kanazawa"],
  ["alps", "קנזאווה", "Omicho Market", "שוק", "sheet", "<b>kaisendon</b>, קערת אורז עם פירות ים. בשעות השיא יש תורים.", "Omicho Market"],
  ["alps", "קנזאווה", "קנזאווה אודן ב-Katamachi", "ארוחת ערב", "sug", "", "Katamachi, Kanazawa"],
  ["alps", "טקאיאמה", "Maruaki", "Hida beef", "sug", "המסעדה לבשר לפי ההערה שלכם. ליד התחנה.", "Maruaki, Takayama"],
  ["alps", "טקאיאמה", "סושי Hida beef", "אוכל רחוב", "sug", "ב-Sanmachi Suji, מוגש על קרקר אורז.", "Sanmachi Suji, Takayama"],
  ["alps", "טקאיאמה", "מבשלות הסאקה", "טעימות", "sug", "מזהים לפי כדור ענפי הארז בכניסה. ברובן יש טעימות.", "Sanmachi Suji, Takayama"],
  ["alps", "מצומוטו ועמק קיסו", "שינשו סובה", "סובה", "sug", "הסובה המקומית של נאגאנו. ב-Onyado Nono מגישים גם ראמן חינם בלילה.", ""],
  ["alps", "מצומוטו ועמק קיסו", "צהריים במגומה", "צהריים", "sug", "לפני ההליכה לצומגו.", "Magome-juku"],
].forEach(([r, area, title, type, src, desc, map, x], i) => DATA.items.push({ id: `f-${r}-${i}`, list: "food:" + r, area, title, type, src, desc, ...(map ? { map } : {}), ...(x || {}), order: i }));
